 #         by Houpq
 # Block commands by worlds with WorldCommandBlocker, only for PocketMine-MP 5.0 servers.
 # Bloquea comandos en cierto mundo con mucha facilidad en la config.yml

# Prefix:
Prefix: "&l&c(&4!&c)&8»&r "
# Config version:
config-version: "2.0.0"
# =======(SETTINGS)=======
# Error message, use "true" or "false" 
# to enable/disable this option
blocked-message: true
# Use:
# & => "§", color
# "{LINE}" => "\n",
# "{NAME}" => $player->getName(), // Player name
# "{WORLD_NAME}" => $player->getWorld()->getDisplayName(), // World name
error-message: "&cEste comando esta bloqueado en este mundo."
# Here you will be able to block many 
# commands with the following example:
# ===================== #
# Settings:             #
#   blocked-commands:   #
#     world name:       #
#       - commando here #
#       - gamemode      #
# ===================== #
Settings:
  blocked-commands:
    Lobby:
      - sethome
      - me
      - say
    MinaPvP:
      - sethome
      - warp
      - hub
      - kit
